name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print hello world
        run: echo "Hello World!"

      - name: Print current date and time
        run: date

      - name: Print current working directory
        run: ls
