name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  print_hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: print hello world
        run: |
          echo "Hello World!"
