name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install
        working-directory: ./fso-pokedex

      - name: Lint Project
        run: npm run eslint
        working-directory: ./fso-pokedex

      - name: Build Project
        run: npm run build
        working-directory: ./fso-pokedex

      - name: Run Tests
        run: npm test
        working-directory: ./fso-pokedex
