name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setp-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Lint Project
        run: npm run lint
